"use client";
import { useState, useMemo } from "react";
import { ReportCard } from "@/components/ui/ReportCard";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Search, SlidersHorizontal, AlertCircle } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { CardSkeleton } from "@/components/skeletons/CardSkeleton";

export default function ExplorePage() {
  const [searchQuery, setSearchQuery] = useState("");
  const [filterCategory, setFilterCategory] = useState("All");
  const [sortBy, setSortBy] = useState("newest");

  const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000/api";

  const { data, isLoading, isError, error } = useQuery({
    queryKey: ["items"],
    queryFn: async () => {
      const res = await fetch(`${API_URL}/items`);
      if (!res.ok) throw new Error("Failed to fetch reports");
      return res.json();
    },
    retry: 1
  });

  const reports = data?.data || [];

  const filteredAndSortedItems = useMemo(() => {
    let result = [...reports];

    // Filter by Category
    if (filterCategory !== "All") {
      result = result.filter(item => item.category === filterCategory);
    }

    // Filter by Search Query
    if (searchQuery.trim()) {
      const lowerQuery = searchQuery.toLowerCase();
      result = result.filter(item => 
        (item.title && item.title.toLowerCase().includes(lowerQuery)) ||
        (item.description && item.description.toLowerCase().includes(lowerQuery))
      );
    }

    // Sort
    result.sort((a, b) => {
      const dateA = new Date(a.createdAt).getTime();
      const dateB = new Date(b.createdAt).getTime();
      if (sortBy === "newest") {
        return dateB - dateA;
      } else {
        return dateA - dateB;
      }
    });

    return result;
  }, [reports, filterCategory, searchQuery, sortBy]);

  return (
    <div className="min-h-screen bg-background flex flex-col">
      {/* Top Bar for Filters and Search */}
      <div className="sticky top-16 z-40 bg-background/80 backdrop-blur-md border-b border-border shadow-sm">
        <div className="max-w-[1600px] mx-auto px-6 py-4 flex flex-col sm:flex-row gap-4 items-center justify-between">
          <div className="relative w-full sm:max-w-md">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
            <Input 
              placeholder="Search reports..." 
              className="pl-9 bg-background focus-visible:ring-primary/50 shadow-sm"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
            />
          </div>
          <div className="flex gap-2 w-full sm:w-auto overflow-x-auto pb-2 sm:pb-0 hide-scrollbar items-center">
            {["All", "Finance", "Marketing", "Operations", "Sales", "Data Analysis"].map((cat) => (
              <Button 
                key={cat} 
                variant={cat === filterCategory ? "default" : "outline"} 
                className="whitespace-nowrap rounded-full shadow-sm"
                onClick={() => setFilterCategory(cat)}
              >
                {cat}
              </Button>
            ))}
            
            <select 
              value={sortBy}
              onChange={(e) => setSortBy(e.target.value)}
              className="ml-auto sm:ml-2 h-9 items-center justify-center rounded-md border border-input bg-background px-3 py-1 text-sm shadow-sm transition-colors focus:outline-none focus:ring-1 focus:ring-ring"
            >
              <option value="newest">Newest First</option>
              <option value="oldest">Oldest First</option>
            </select>
            <Button variant="outline" size="icon" className="shrink-0 rounded-full shadow-sm hidden">
              <SlidersHorizontal className="w-4 h-4" />
            </Button>
          </div>
        </div>
      </div>

      {/* Grid Area */}
      <main className="flex-1 max-w-[1600px] w-full mx-auto px-6 py-8">
        <div className="mb-8">
          <h1 className="text-3xl font-bold tracking-tight">Explore Reports</h1>
          <p className="text-muted-foreground mt-2">Discover insights and analytics generated by your team.</p>
        </div>

        {/* Displaying 4 cards per row on large desktop, responsive below that */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
          {isLoading ? (
            Array.from({ length: 8 }).map((_, i) => <CardSkeleton key={i} />)
          ) : isError ? (
            <div className="col-span-full flex flex-col items-center justify-center p-12 text-destructive border border-destructive/20 rounded-lg bg-destructive/5">
              <AlertCircle className="w-10 h-10 mb-4" />
              <h3 className="text-xl font-bold">Error Loading Reports</h3>
              <p className="text-sm opacity-80 mt-2">{error?.message || "Could not connect to the backend server."}</p>
            </div>
          ) : filteredAndSortedItems.length === 0 ? (
            <div className="col-span-full flex justify-center p-12 text-muted-foreground">
              No reports found matching your criteria.
            </div>
          ) : (
            filteredAndSortedItems.map((report: any, i: number) => (
              <ReportCard
                key={report._id}
                id={report._id}
                title={report.title}
                description={report.description}
                date={new Date(report.createdAt).toLocaleDateString()}
                category={report.category}
                imageUrl={report.fileUrl || `https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=400&h=300&random=${i}`}
              />
            ))
          )}
        </div>
      </main>
    </div>
  );
}
