import { ReportCard } from "@/components/ui/ReportCard";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Search, SlidersHorizontal } from "lucide-react";

export default function ExplorePage() {
  // Realistic dummy data
  const reports = Array.from({ length: 12 }).map((_, i) => ({
    id: i,
    title: `Q${(i % 4) + 1} Financial Analysis ${2024 - Math.floor(i / 4)}`,
    description: "Comprehensive breakdown of revenue, expenses, and profit margins across all regional sectors with predictive modeling for the upcoming quarter.",
    date: new Date(Date.now() - i * 1000000000).toLocaleDateString(),
    category: ["Finance", "Marketing", "Operations", "Sales"][i % 4],
    imageUrl: `https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=400&h=300&random=${i}`
  }));

  return (
    <div className="min-h-screen bg-background flex flex-col">
      {/* Top Bar for Filters and Search */}
      <div className="sticky top-16 z-40 bg-background/80 backdrop-blur-md border-b border-border shadow-sm">
        <div className="max-w-[1600px] mx-auto px-6 py-4 flex flex-col sm:flex-row gap-4 items-center justify-between">
          <div className="relative w-full sm:max-w-md">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
            <Input 
              placeholder="Search reports..." 
              className="pl-9 bg-background focus-visible:ring-primary/50 shadow-sm"
            />
          </div>
          <div className="flex gap-2 w-full sm:w-auto overflow-x-auto pb-2 sm:pb-0 hide-scrollbar">
            {["All", "Finance", "Marketing", "Operations", "Sales"].map((cat) => (
              <Button key={cat} variant={cat === "All" ? "default" : "outline"} className="whitespace-nowrap rounded-full shadow-sm">
                {cat}
              </Button>
            ))}
            <Button variant="outline" size="icon" className="shrink-0 rounded-full ml-auto sm:ml-2 shadow-sm">
              <SlidersHorizontal className="w-4 h-4" />
            </Button>
          </div>
        </div>
      </div>

      {/* Grid Area */}
      <main className="flex-1 max-w-[1600px] w-full mx-auto px-6 py-8">
        <div className="mb-8">
          <h1 className="text-3xl font-bold tracking-tight">Explore Reports</h1>
          <p className="text-muted-foreground mt-2">Discover insights and analytics generated by your team.</p>
        </div>

        {/* Displaying 4 cards per row on large desktop, responsive below that */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
          {reports.map((report) => (
            <ReportCard
              key={report.id}
              title={report.title}
              description={report.description}
              date={report.date}
              category={report.category}
              imageUrl={report.imageUrl}
            />
          ))}
        </div>
      </main>
    </div>
  );
}
